export const SUCCESS = "SUCCESS";
export const AI_PROMPT_TOO_LONG = "AI_PROMPT_TOO_LONG";
export const FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED";
export const MAX_RETRIES_EXCEEDED = "MAX_RETRIES_EXCEEDED";
export const ANSWER_TO_BE_GRADED_TO_LONG = "ANSWER_TO_BE_GRADED_TO_LONG";
